---
app: docker-create-react-app
auto_deploy: true
context: release-customer-us-west-2
domain: docker-create-react-app.rls.sh
mode: development
repo_name: elanderholm/docker-create-react-app
hostnames:
- app: app-${env_id}-${domain}
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
services:
- name: app
  image: elanderholm/docker-create-react-app/app
  build:
    context: "."
  has_repo: true
  static: false
  args:
  - npm
  - start
  ports:
  - type: node_port
    target_port: '4000'
    port: '4000'
workflows:
- name: setup
  order_from:
  - services.all
- name: patch
  order_from:
  - services.app
app_imports:
- name: rails-postgres-redis

